"use client";

import { useState } from "react";
import { Activity, AlertTriangle, Bell, Beef as Cow, Camera, Check, ChevronDown, CircleDollarSign, ClipboardCheck, CloudSun, FileText, Gauge, Inbox, Leaf, Map, Menu, Mic, Package, Plus, ScanLine, Search, Settings, ShoppingCart, Sprout, Tractor, TrendingUp, Video, Wheat, X } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Toaster, toast } from "sonner";

type View = "dashboard"|"parcelles"|"troupeau"|"passeport"|"diagnostic"|"stocks"|"cameras"|"pac"|"fournisseurs"|"admin"|"finances"|"marches"|"meteo"|"journal";
const nav = [
 ["dashboard","Centre de contrôle",Gauge],["parcelles","Parcelles & intrants",Tractor],["troupeau","Troupeau",Cow],["passeport","Scan passeport",ScanLine],["diagnostic","Diagnostic blé",Sprout],["stocks","Foin & stocks",Package],["cameras","Caméras DMSS",Video],["pac","PAC & Géoportail",Map],["fournisseurs","Fournisseurs & achats",ShoppingCart],["admin","Mails & factures",Inbox],["finances","Finances",CircleDollarSign],["marches","Cotations",TrendingUp],["meteo","Météo",CloudSun],["journal","Journal",ClipboardCheck]
] as const;
const companies=["Toutes les entreprises","EARL Artemis","SCEA Vatan et fils","SCEA des Bonnédanes"];
const parcels=[["Les Bordos","13,10 ha","Blé tendre","Artemis","Bon"],["Les Grandes","24,50 ha","Maïs","Vatan","Bon"],["Pré du Moulin","18,20 ha","Prairie","Bonnédanes","À surveiller"],["La Croix","31,80 ha","Colza","Vatan","Bon"],["Les Saules","16,40 ha","Blé tendre","Artemis","Bon"],["Champ Rond","27,30 ha","Orge","Bonnédanes","Intervention"],["La Vallée","42,70 ha","Prairie","Vatan","Bon"],["Les Coteaux","21,60 ha","Tournesol","Artemis","Bon"]];
const animals=[["62-30","FR 18 4125 6230","F · Charolaise","12 fév. 2027","4125","EARL Artemis"],["62-28","FR 18 4125 6228","M · Charolais","28 jan. 2027","4098","EARL Artemis"],["61-94","FR 18 5531 6194","F · Charolaise","08 déc. 2026","3981","SCEA Vatan"],["61-87","FR 18 5531 6187","M · Charolais","21 nov. 2026","3912","SCEA Vatan"]];
const journal=[["09:42","Intervention enregistrée","Les Bordos · Engrais N · 150 kg/ha","EARL Artemis"],["08:16","Facture classée","AGRIAL · FAC-2027-184 · 4 280 €","SCEA Vatan"],["02:14","Alerte vêlage détectée","CAM-01 · Confiance 87 % · Veau 62-30","EARL Artemis"],["Hier","Commande fournisseur validée","Distri Agri · GNR 4 000 L · 1,08 €/L","EARL Artemis"]];

function Title({kicker,title,action}:{kicker:string,title:string,action?:React.ReactNode}){return <div className="title"><div><span>{kicker}</span><h1>{title}</h1></div>{action}</div>}
function Status({children,warn=false}:{children:React.ReactNode,warn?:boolean}){return <span className={`status ${warn?"warn":""}`}><i/>{children}</span>}
function Metric({label,value,note,icon:Icon,tone="green"}:any){return <div className="metric"><div className={`metric-icon ${tone}`}><Icon/></div><div><span>{label}</span><b>{value}</b><small>{note}</small></div></div>}

function Dashboard({go,voice}:{go:(v:View)=>void,voice:()=>void}){return <div className="view">
 <div className="welcome"><div><span>LUNDI 28 FÉVRIER 2027</span><h1>Bonjour Alexandre</h1><p>Voici l’essentiel de vos trois exploitations ce matin.</p></div><div className="weather"><CloudSun/><b>12°C</b><small>Vent 15 km/h · Sol portant</small></div></div>
 <div className="metrics"><Metric label="Trésorerie disponible" value="186 240 €" note="+ 8,4 % ce mois" icon={CircleDollarSign}/><Metric label="Factures à traiter" value="7" note="18 460 € à échéance" icon={FileText} tone="amber"/><Metric label="Blé disponible" value="200 T" note="44 400 € au prix actuel" icon={Wheat} tone="earth"/><Metric label="Vêlages ce mois" value="12 / 18" note="1 alerte cette nuit" icon={Cow} tone="red"/></div>
 <div className="dash-grid">
  <section className="card camera-card"><Title kicker="SURVEILLANCE" title="Caméras en direct" action={<button className="link" onClick={()=>go("cameras")}>Voir les 4 caméras</button>}/><div className="feeds"><button className="feed main-feed" onClick={()=>go("cameras")}><div className="barn"/><span className="live">● LIVE</span><span className="alert"><AlertTriangle/> Vêlage probable 87 %</span><label><b>CAM-01 · Vêlages</b><small>PTZ 5MP · Hangar nord</small></label></button><div className="feed small"><div className="barn alt"/><span className="live">● LIVE</span><label><b>CAM-02 · Contention</b></label></div><div className="feed small"><div className="barn road"/><span className="live">● LIVE</span><label><b>CAM-03 · Entrée</b></label></div></div></section>
  <section className="card priority"><Title kicker="À VALIDER" title="Alertes prioritaires" action={<b className="count">3</b>}/><div className="notice red"><Cow/><div><b>Vêlage probable · 87 %</b><span>CAM-01 · 02:14 · Veau 62-30</span><button onClick={()=>toast.success("Capture liée au veau 62-30")}>Lier au veau</button></div></div><div className="notice amber"><FileText/><div><b>2 factures arrivent à échéance</b><span>8 740 € · avant le 3 mars</span><button onClick={()=>go("admin")}>Vérifier</button></div></div><div className="notice green"><Sprout/><div><b>Fenêtre traitement favorable</b><span>Les Bordos · 6–7 mai</span><button onClick={()=>go("diagnostic")}>Voir le diagnostic</button></div></div></section>
  <section className="card map-card"><Title kicker="EXPLOITATIONS" title="Vue parcellaire"/><div className="farm-map"><button className="plot p1" onClick={()=>go("parcelles")}>Les Bordos<small>13,10 ha · Blé</small></button><button className="plot p2">Les Grandes<small>24,50 ha · Maïs</small></button><button className="plot p3">Pré du Moulin<small>18,20 ha · Prairie</small></button><i className="pin"><Camera/></i></div></section>
  <section className="card activity-card"><Title kicker="TRAÇABILITÉ" title="Dernières activités" action={<button className="link" onClick={()=>go("journal")}>Tout le journal</button>}/>{journal.map((j,i)=><div className="activity" key={j[1]}><i className={`d${i}`}/><div><b>{j[1]}</b><span>{j[2]}</span></div><time>{j[0]}</time></div>)}</section>
 </div><button className="voice-fab" onClick={voice}><Mic/>Parler à AgriPilot <kbd>⌘ K</kbd></button>
 </div>}

function Parcelles(){const [selected,setSelected]=useState(0);const [open,setOpen]=useState(false);return <div className="view"><Title kicker="483 HA SAU · 8 PARCELLES ACTIVES" title="Parcelles & intrants" action={<button className="primary" onClick={()=>setOpen(true)}><Plus/>Nouvelle intervention</button>}/><div className="split"><section className="card table-card"><div className="tools"><label><Search/><input placeholder="Rechercher une parcelle…"/></label><button>Toutes les cultures <ChevronDown/></button></div><div className="table"><div className="row head"><span>Parcelle</span><span>Culture</span><span>Société</span><span>État</span></div>{parcels.map((p,i)=><button className={`row ${i===selected?"selected":""}`} onClick={()=>setSelected(i)} key={p[0]}><span><b>{p[0]}</b><small>{p[1]}</small></span><span>{p[2]}</span><span>{p[3]}</span><span><Status warn={p[4]!=="Bon"}>{p[4]}</Status></span></button>)}</div></section><aside className="card detail"><div className="field-photo"><Wheat/></div><span>EARL {parcels[selected][3]}</span><h2>{parcels[selected][0]}</h2><b className="big">{parcels[selected][1]}</b><dl><div><dt>Coût campagne</dt><dd>38 €/ha</dd></div><div><dt>Dernière intervention</dt><dd>28 fév. 2027</dd></div><div><dt>État du sol</dt><dd>Portant</dd></div></dl><h3>Historique récent</h3><p>Engrais N · 150 kg/ha<small>Aujourd’hui · Validé par Alexandre</small></p><p>Diagnostic Z32<small>15 % septoriose F3</small></p></aside></div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Nouvelle intervention</DialogTitle><DialogDescription>Vérifiez les données avant enregistrement.</DialogDescription></DialogHeader><div className="form"><label>Parcelle<select><option>Les Bordos · 13,10 ha</option></select></label><label>Type<select><option>Engrais</option><option>Fongicide</option></select></label><label>Produit<input defaultValue="Engrais N 32"/></label><label>Dose (kg/ha)<input defaultValue="150"/></label><label>Azote (unités)<input defaultValue="48"/></label><label>Surface<input defaultValue="13,10 ha"/></label></div><div className="calc"><span>Total calculé</span><b>1 965 kg · 38 €/ha</b><small>Stock après validation : 1,235 T</small></div><button className="primary full" onClick={()=>{setOpen(false);toast.success("Intervention enregistrée dans le Journal")}}><Check/>Valider l’intervention</button></DialogContent></Dialog></div>}

function Troupeau(){return <div className="view"><Title kicker="150 MÈRES · 184 ANIMAUX PRÉSENTS" title="Troupeau" action={<button className="primary" onClick={()=>toast.info("Déclaration pré-remplie — validation requise")}><Plus/>Déclarer une naissance</button>}/><div className="metrics"><Metric label="Animaux présents" value="184" note="150 mères · 34 veaux" icon={Cow}/><Metric label="Naissances 2027" value="18" note="12 ce mois" icon={Activity} tone="earth"/><Metric label="UGB estimées" value="162,4" note="Calcul Boviclic simulé" icon={Gauge} tone="amber"/><Metric label="Ventes 2027" value="24 860 €" note="+ 4,2 % vs cotation" icon={TrendingUp}/></div><section className="card table-card"><div className="tools"><label><Search/><input placeholder="N° travail, national, mère…"/></label><Status>Boviclic synchronisé</Status></div><div className="table herd"><div className="row head"><span>N° travail</span><span>N° national</span><span>Sexe / race</span><span>Naissance</span><span>Mère</span><span>Société</span></div>{animals.map(a=><div className="row" key={a[0]}>{a.map((x,i)=><span key={x}>{i===0?<b>{x}</b>:x}{i===0&&x==="62-30"&&<small>Capture CAM-01 · 02:14</small>}</span>)}</div>)}</div></section></div>}

function Passport(){const [done,setDone]=useState(false);return <div className="view"><Title kicker="OCR BOVIN · MODE HORS-LIGNE" title="Scan passeport"/><div className="scan-grid"><section className="scanner card"><div className={`scan-frame ${done?"done":""}`}><div className="passport"><b>IDENTIFICATION BOVINE</b><strong>FR 18 4125 6230</strong><span>62-30 · CHAROLAISE · 12/02/2027</span></div>{!done&&<i/>}</div><button onClick={()=>setDone(true)}><Camera/></button><span>{done?"Analyse terminée":"Cadrez le passeport rose"}</span></section><section className="card extracted"><Title kicker={done?"CONFIANCE MOYENNE 96 %":"EN ATTENTE D’UNE PHOTO"} title="Données extraites"/>{done?<><div className="form"><label>N° national<input value="FR 18 4125 6230" readOnly/></label><label>N° travail<input value="62-30" readOnly/></label><label>Race<input value="Charolaise" readOnly/></label><label>Sexe<input value="Femelle" readOnly/></label><label>Date de naissance<input value="12/02/2027" readOnly/></label><label>Entreprise<select><option>SCEA Vatan et fils</option><option>EARL Artemis</option></select></label></div><div className="human"><Check/><div><b>Validation humaine obligatoire</b><span>Aucun envoi à Boviclic avant votre accord.</span></div></div><button className="primary full" onClick={()=>toast.success("Animal créé · Boviclic en attente")}><Check/>Créer dans le cheptel</button></>:<div className="empty"><ScanLine/><p>Les champs OCR apparaîtront ici.</p></div>}</section></div></div>}

function Diagnostic(){const [ok,setOk]=useState(false);return <div className="view"><Title kicker="ANALYSE AGRONOMIQUE ASSISTÉE" title="Diagnostic blé" action={<button className="primary"><Camera/>Photographier un pied</button>}/><div className="diag-grid"><section className="card crop"><div><Wheat/><i/></div><p><span>Les Bordos · 13,10 ha</span><b>Photo prise aujourd’hui à 10:18</b></p></section><section className="card diagnosis"><Title kicker="RÉSULTAT DE L’ANALYSE" title="Stade Z32 · 2 nœuds"/>{[["Septoriose · F3",75,"15 %"],["Rouille brune",1,"0 %"],["Oïdium",8,"Traces"]].map(x=><div className="disease"><label>{x[0]} <b>{x[2]}</b></label><Progress value={Number(x[1])}/></div>)}</section><section className="card recommendation"><AlertTriangle/><span>SEUIL DÉPASSÉ</span><h2>Traitement recommandé</h2><div className="product"><b>Revystar</b><span>0,8 L/ha · DAR 35 jours</span><strong>42 €/ha · 550 € total</strong></div><div className="forecast"><CloudSun/><div><b>Fenêtre favorable : 6–7 mai</b><span>12°C · vent 15 km/h · sans pluie</span></div></div><button className="primary full" onClick={()=>{setOk(true);toast.success("Tâche créée, stock phyto mis à jour")}}>{ok?<><Check/>Traitement validé</>:"Valider et créer la tâche"}</button></section></div></div>}

function Cameras(){return <div className="view"><Title kicker="NVR DAHUA · 4 CAMÉRAS CONNECTÉES" title="Caméras DMSS" action={<Status>go2rtc sécurisé</Status>}/><div className="cam-grid">{["Vêlages · PTZ 5MP","Contention · Dome 4MP","Entrée · Bullet 8MP","Foin · Bullet 4MP"].map((c,i)=><section className="card cam" key={c}><div className={`cam-view v${i}`}><div className="barn"/><span className="live">● LIVE</span></div><footer><div><b>CAM-0{i+1} · {c}</b><span>Connexion sécurisée</span></div><button onClick={()=>toast.success("Capture ajoutée au Journal")}><Camera/></button></footer></section>)}</div></div>}

function Suppliers(){return <div className="view"><Title kicker="8 FAMILLES · 35 SOUS-CATÉGORIES" title="Fournisseurs & achats" action={<button className="primary"><Plus/>Nouveau besoin</button>}/><div className="supplier-grid"><section className="card need"><span>DEMANDE EN COURS</span><h2>4 000 L de fuel</h2><p>EARL Artemis · Livraison avant le 5 mars</p>{[["Distri Agri","1,08 €/L · Livraison 48h","4 320 €"],["Énergies Centre","1,11 €/L · Livraison 24h","4 440 €"]].map((q,i)=><label className="quote"><input type="radio" name="q" defaultChecked={!i}/><div><b>{q[0]}</b><span>{q[1]}</span></div><strong>{q[2]}</strong></label>)}<div className="human"><Check/><div><b>Brouillon prêt</b><span>Relisez avant tout envoi externe.</span></div></div><button className="primary full" onClick={()=>toast.success("Commande validée et journalisée")}>Valider Distri Agri</button></section><section className="card suppliers"><Title kicker="AUTO-DÉTECTION DEPUIS LES FACTURES" title="Fournisseurs récents"/>{[["AGRIAL","Alimentation animale","64 800 €"],["Distri Agri","Énergie & carburant","43 200 €"],["Terres Inovia","Agrofourniture","31 900 €"],["Garage Moreau","Matériel & SAV","18 400 €"]].map(s=><div className="supplier"><i>{s[0][0]}</i><div><b>{s[0]}</b><span>{s[1]}</span></div><strong>{s[2]}</strong></div>)}</section></div></div>}

function Admin(){return <div className="view"><Title kicker="3 BOÎTES CONNECTÉES · ANALYSE AUTOMATIQUE" title="Mails & factures"/><div className="mail-grid"><section className="card invoices">{[["AGRIAL","FAC-2027-184","4 280 €","3 mars"],["Garage Moreau","GM-8842","2 940 €","8 mars"],["Distri Agri","DA-0227","4 320 €","12 mars"],["Vétérinaire du Berry","VB-947","1 180 €","15 mars"]].map((m,i)=><button className={i===0?"active":""}><div><b>{m[0]}</b><span>{m[1]} · EARL Artemis</span></div><strong>{m[2]}</strong><small>Échéance {m[3]}</small></button>)}</section><section className="card invoice-detail"><Title kicker="FACTURE DÉTECTÉE" title="AGRIAL · FAC-2027-184" action={<Status warn>À vérifier</Status>}/><div className="paper"><b>AGRIAL</b><i/><i/><i/><strong>TOTAL TTC　4 280,00 €</strong></div><div className="invoice-fields"><div><span>Entreprise</span><b>EARL Artemis</b></div><div><span>Échéance</span><b>03/03/2027</b></div><div><span>Doublon</span><b>Aucun détecté</b></div></div><button className="primary full" onClick={()=>toast.success("Facture validée et classée")}><Check/>Valider et classer</button></section></div></div>}

function Finances(){return <div className="view"><Title kicker="VUE CONSOLIDÉE · EXERCICE 2027" title="Finances"/><div className="metrics"><Metric label="CA prévisionnel" value="684 200 €" note="+ 6,8 % vs N-1" icon={TrendingUp}/><Metric label="Charges engagées" value="397 960 €" note="58 % du CA" icon={ShoppingCart} tone="earth"/><Metric label="Créances" value="62 480 €" note="3 paiements attendus" icon={FileText} tone="amber"/><Metric label="Marge prévisionnelle" value="286 240 €" note="41,8 %" icon={CircleDollarSign}/></div><section className="card chart"><Title kicker="MARGE PAR ACTIVITÉ" title="Performance consolidée"/><div className="bars">{[["Blé",88],["Bovins",68],["Maïs",58],["Prairies",39],["Colza",52]].map(x=><div><b>{(Number(x[1])*1210).toLocaleString("fr-FR")} €</b><i style={{height:`${x[1]}%`}}/><span>{x[0]}</span></div>)}</div></section></div>}

function Journal(){return <div className="view"><Title kicker="AUDIT PAC, COMPTABILITÉ ET ASSURANCE" title="Journal & traçabilité" action={<button className="secondary">Exporter Sheets</button>}/><section className="card journal">{journal.map(j=><div><i><Activity/></i><main><time>{j[0]}</time><h3>{j[1]}</h3><p>{j[2]}</p><span>{j[3]}</span><span><Check/>Validé par Alexandre</span></main></div>)}</section></div>}

function Simple({view}:{view:View}){const data:any={stocks:["Foin & stocks","420 T DE CAPACITÉ HANGAR",Package],pac:["PAC & Géoportail","RPG, CADASTRE ET PREUVES TERRAIN",Map],marches:["Cotations marchés","FMBV + MATIF",TrendingUp],meteo:["Météo agricole","CONDITIONS ET FENÊTRES D’INTERVENTION",CloudSun]};let [t,k,I]=data[view];return <div className="view"><Title kicker={k} title={t}/><div className="simple-grid">{(view==="stocks"?[["Foin","284 T",68],["Paille","96 T",52],["Enrubannage","74 T",44],["Engrais N","1,235 T",39]]:[["Aujourd’hui","12°C",74],["Demain","14°C",55],["Mercredi","16°C",42],["Jeudi","15°C",81]]).map(x=><section className="card stat"><I/><span>{x[0]}</span><b>{x[1]}</b><Progress value={Number(x[2])}/></section>)}</div><section className="card feature"><I/><h2>{view==="pac"?"483 ha contrôlés":view==="marches"?"Blé à 222 €/T":"Vue consolidée"}</h2><p>{view==="pac"?"Superposition RPG, orthophoto et cadastre avec preuves photo liées.":view==="marches"?"Prix réalisé : +4 € par rapport au marché du jour.":"Données rattachées à chaque entreprise."}</p><button className="primary" onClick={()=>toast.info("Connexion externe simulée dans cette version")}>Actualiser les données</button></section></div>}

function Voice({open,close,go}:{open:boolean,close:()=>void,go:(v:View)=>void}){const [listen,setListen]=useState(false);function run(v:View){setTimeout(()=>{go(v);close();toast.success("Commande comprise · formulaire pré-rempli")},300)}return <Dialog open={open} onOpenChange={close}><DialogContent className="voice-dialog"><DialogHeader><DialogTitle>Agent vocal AgriPilot</DialogTitle><DialogDescription>Parlez naturellement. Vous validerez toujours avant enregistrement.</DialogDescription></DialogHeader><button className={`voice-orb ${listen?"on":""}`} onClick={()=>setListen(!listen)}><Mic/></button><b>{listen?"Je vous écoute…":"Touchez le micro pour parler"}</b><div className="samples"><button onClick={()=>run("parcelles")}>Épandage sur Les Bordos</button><button onClick={()=>run("troupeau")}>Déclarer la naissance 62-30</button><button onClick={()=>run("cameras")}>Montre la caméra vêlage</button><button onClick={()=>run("fournisseurs")}>Demande prix à deux fournisseurs</button></div></DialogContent></Dialog>}

export default function Page(){const [view,setView]=useState<View>("dashboard"),[company,setCompany]=useState(0),[terrain,setTerrain]=useState(false),[menu,setMenu]=useState(false),[voice,setVoice]=useState(false);let content=view==="dashboard"?<Dashboard go={setView} voice={()=>setVoice(true)}/>:view==="parcelles"?<Parcelles/>:view==="troupeau"?<Troupeau/>:view==="passeport"?<Passport/>:view==="diagnostic"?<Diagnostic/>:view==="cameras"?<Cameras/>:view==="fournisseurs"?<Suppliers/>:view==="admin"?<Admin/>:view==="finances"?<Finances/>:view==="journal"?<Journal/>:<Simple view={view}/>;return <div className={terrain?"app terrain":"app"}><aside className={menu?"sidebar open":"sidebar"}><div className="brand"><i><Leaf/></i><div><b>AgriPilot</b><span>OS Agricole</span></div><button onClick={()=>setMenu(false)}><X/></button></div><button className="company" onClick={()=>setCompany((company+1)%companies.length)}><i>{companies[company][0]}</i><div><span>Vue active</span><b>{companies[company]}</b></div><ChevronDown/></button><nav>{nav.map(([id,label,I])=><button className={view===id?"active":""} onClick={()=>{setView(id as View);setMenu(false)}}><I/><span>{label}</span>{id==="admin"&&<b>7</b>}</button>)}</nav><footer><button><Settings/>Réglages</button><div><i>AC</i><span><b>Alexandre Cresson</b><small>Administrateur</small></span></div></footer></aside><main className="content"><header><button className="menu" onClick={()=>setMenu(true)}><Menu/></button><b>{nav.find(x=>x[0]===view)?.[1]}</b><div><button className="mode" onClick={()=>setTerrain(!terrain)}><Tractor/>{terrain?"Mode cockpit":"Mode terrain"}</button><button><Search/></button><button><Bell/></button></div></header>{content}</main>{terrain&&<div className="bottom"><button onClick={()=>setView("dashboard")}><Gauge/>Accueil</button><button onClick={()=>setView("parcelles")}><Tractor/>Parcelle</button><button className="mic" onClick={()=>setVoice(true)}><Mic/></button><button onClick={()=>setView("passeport")}><ScanLine/>Scanner</button><button onClick={()=>setView("cameras")}><Video/>Caméras</button></div>}<Voice open={voice} close={()=>setVoice(false)} go={setView}/><Toaster position="top-right" richColors/></div>}
