"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-expressions, @next/next/no-img-element, react-hooks/set-state-in-effect, react-hooks/purity */

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Activity, Beef, Bell, Camera, Check, ChevronDown, CircleDollarSign, ClipboardCheck, CloudRain, CloudSun, Download, FileText, Gauge, Inbox, Leaf, LogOut, Map, Menu, Mic, Package, Plus, ScanLine, Search, Settings, ShoppingCart, Sprout, Tractor, TrendingUp, Trash2, Upload, Video, Wheat, X } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Toaster, toast } from "sonner";
import { getSupabase, isSupabaseConfigured } from "@/lib/supabase";
import type { Session } from "@supabase/supabase-js";

type View="dashboard"|"parcels"|"animals"|"passport"|"diagnosis"|"stocks"|"cameras"|"pac"|"suppliers"|"invoices"|"finance"|"markets"|"weather"|"journal";
type Company={id:string;name:string;color:string;siret?:string|null};
type Parcel={id:string;company_id:string;name:string;surface_ha:number;culture:string;status:string;cost_per_ha:number};
type Animal={id:string;company_id:string;work_number:string;national_number?:string;sex?:string;breed?:string;birth_date?:string;mother_number?:string;status:string};
type Supplier={id:string;company_id:string;name:string;category:string;subcategory?:string;email?:string;annual_volume:number;status:string};
type Invoice={id:string;company_id:string;supplier_name:string;invoice_number:string;amount:number;due_date?:string;status:string;duplicate:boolean};
type Intervention={id:string;company_id:string;parcel_id:string;performed_at:string;operation_type:string;product?:string;dose_kg_ha?:number;treated_area_ha?:number;cost_per_ha:number;weather?:any};
type Stock={id:string;company_id:string;name:string;category:string;quantity:number;unit:string;minimum_quantity:number;unit_cost:number};
type Diagnostic={id:string;company_id:string;parcel_id?:string;disease:string;confidence:number;recommendation:string;status:string;created_at:string};
type Purchase={id:string;company_id:string;supplier_id?:string;need_text:string;quantity?:string;estimated_amount?:number;status:string};
type Sale={id:string;company_id:string;label:string;amount:number;sold_at:string;category:string};
type Journal={id:string|number;company_id?:string;event_type:string;title:string;details:any;created_at:string};
type Data={companies:Company[];parcels:Parcel[];animals:Animal[];suppliers:Supplier[];invoices:Invoice[];interventions:Intervention[];stocks:Stock[];diagnostics:Diagnostic[];purchases:Purchase[];sales:Sale[];journal:Journal[]};
type MutableTable="parcels"|"animals"|"suppliers"|"invoices"|"interventions"|"stocks"|"diagnostics"|"purchase_orders"|"sales";

const nav=[
 ["dashboard","Centre de contrôle",Gauge],["parcels","Parcelles & intrants",Tractor],["animals","Troupeau",Beef],["passport","Scan passeport",ScanLine],["diagnosis","Diagnostic blé",Sprout],["stocks","Foin & stocks",Package],["cameras","Caméras DMSS",Video],["pac","PAC & Géoportail",Map],["suppliers","Fournisseurs & achats",ShoppingCart],["invoices","Mails & factures",Inbox],["finance","Finances",CircleDollarSign],["markets","Cotations",TrendingUp],["weather","Météo",CloudSun],["journal","Journal",ClipboardCheck]
] as const;

const ids={a:"11111111-1111-4111-8111-111111111111",v:"22222222-2222-4222-8222-222222222222",b:"33333333-3333-4333-8333-333333333333"};
const seed:Data={
 companies:[{id:ids.a,name:"EARL Artemis",color:"#c67c4e"},{id:ids.v,name:"SCEA Vatan et fils",color:"#e3aa00"},{id:ids.b,name:"SCEA des Bonnédanes",color:"#4d7c66"}],
 parcels:[{id:crypto.randomUUID(),company_id:ids.a,name:"Les Bordos",surface_ha:13.1,culture:"Blé tendre",status:"Bon",cost_per_ha:38},{id:crypto.randomUUID(),company_id:ids.v,name:"Les Grandes",surface_ha:24.5,culture:"Maïs",status:"Bon",cost_per_ha:52},{id:crypto.randomUUID(),company_id:ids.b,name:"Pré du Moulin",surface_ha:18.2,culture:"Prairie",status:"À surveiller",cost_per_ha:21}],
 animals:[{id:crypto.randomUUID(),company_id:ids.a,work_number:"62-30",national_number:"FR 18 4125 6230",sex:"F",breed:"Charolaise",birth_date:"2027-02-12",mother_number:"4125",status:"Présent"},{id:crypto.randomUUID(),company_id:ids.v,work_number:"61-94",national_number:"FR 18 5531 6194",sex:"F",breed:"Charolaise",birth_date:"2026-12-08",mother_number:"3981",status:"Présent"}],
 suppliers:[{id:crypto.randomUUID(),company_id:ids.a,name:"AGRIAL",category:"Alimentation animale",annual_volume:64800,status:"active"},{id:crypto.randomUUID(),company_id:ids.a,name:"Distri Agri",category:"Énergie & carburant",annual_volume:43200,status:"active"}],
 invoices:[{id:crypto.randomUUID(),company_id:ids.a,supplier_name:"AGRIAL",invoice_number:"FAC-2027-184",amount:4280,due_date:"2027-03-03",status:"pending",duplicate:false}],
 interventions:[],
 stocks:[{id:crypto.randomUUID(),company_id:ids.a,name:"Foin prairie",category:"Fourrage",quantity:86,unit:"balles",minimum_quantity:30,unit_cost:32},{id:crypto.randomUUID(),company_id:ids.a,name:"Ammonitrate 33,5",category:"Engrais",quantity:2400,unit:"kg",minimum_quantity:500,unit_cost:.58}],
 diagnostics:[],purchases:[],sales:[{id:crypto.randomUUID(),company_id:ids.a,label:"Vente céréales",amount:18400,sold_at:new Date().toISOString().slice(0,10),category:"Cultures"}],
 journal:[{id:1,company_id:ids.a,event_type:"seed",title:"Espace de démonstration initialisé",details:{},created_at:new Date().toISOString()}]
};

function titleForCompany(data:Data,id:string){return data.companies.find(c=>c.id===id)?.name||"Entreprise"}
function money(n:number){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n)}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Title({kicker,title,action}:{kicker:string;title:string;action?:React.ReactNode}){return <div className="title"><div><span>{kicker}</span><h1>{title}</h1></div>{action}</div>}
function Status({children,warn=false}:{children:React.ReactNode;warn?:boolean}){return <span className={`status ${warn?"warn":""}`}><i/>{children}</span>}

function Auth({onSession}:{onSession:(s:Session)=>void}){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);const sb=getSupabase();const result=signup?await sb.auth.signUp({email,password,options:{data:{full_name:email.split("@")[0]}}}):await sb.auth.signInWithPassword({email,password});setBusy(false);if(result.error)return toast.error(result.error.message);if(result.data.session)onSession(result.data.session);else setConfirmation(true)}
 async function resend(){setBusy(true);const {error}=await getSupabase().auth.resend({type:"signup",email});setBusy(false);error?toast.error(error.message):toast.success("E-mail de confirmation renvoyé")}
 return <main className="auth-page"><section className="auth-card"><div className="auth-brand"><i><Leaf/></i><div><b>AgriPilot</b><span>OS Agricole</span></div></div>{confirmation?<><h1>Confirmez votre e-mail</h1><p>Un lien a été envoyé à <b>{email}</b>. Ouvrez-le puis revenez vous connecter.</p><button className="primary full" onClick={resend} disabled={busy}>Renvoyer le lien</button><button className="auth-link" onClick={()=>{setConfirmation(false);setSignup(false)}}>Retour à la connexion</button></>:<><h1>{signup?"Créer le premier compte":"Connexion"}</h1><p>Accédez aux données autorisées de vos exploitations.</p><form onSubmit={submit}><Field label="Adresse e-mail"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></Field><Field label="Mot de passe"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></Field><button className="primary full" disabled={busy}>{busy?"Patientez…":signup?"Créer le compte":"Se connecter"}</button></form><button className="auth-link" onClick={()=>setSignup(!signup)}>{signup?"J’ai déjà un compte":"Créer un compte"}</button></>}</section></main>
}

function useCrmData(session:Session|null){
 const cloud=isSupabaseConfigured();const [data,setData]=useState<Data>(seed),[loading,setLoading]=useState(cloud),[error,setError]=useState<string|null>(null);
 const persist=(next:Data)=>{setData(next);if(!cloud)localStorage.setItem("agripilot-demo",JSON.stringify(next))};
 const load=useCallback(async()=>{
  if(!cloud){const saved=localStorage.getItem("agripilot-demo");if(saved)try{const parsed=JSON.parse(saved);setData({...seed,...parsed,interventions:parsed.interventions||[],stocks:parsed.stocks||seed.stocks,diagnostics:parsed.diagnostics||[],purchases:parsed.purchases||[],sales:parsed.sales||seed.sales})}catch{}setLoading(false);return}
  if(!session)return;setLoading(true);const sb=getSupabase();
  const access=await sb.from("user_company_access").select("company_id, companies(id,name,color,siret)");
  if(access.error){setError(access.error.message);setLoading(false);return}
  const companies=(access.data||[]).map((x:any)=>x.companies).filter(Boolean) as Company[];
  const [p,a,s,i,int,st,d,po,sa,j]=await Promise.all([sb.from("parcels").select("*").order("name"),sb.from("animals").select("*").order("created_at",{ascending:false}),sb.from("suppliers").select("*").order("name"),sb.from("invoices").select("*").order("due_date"),sb.from("interventions").select("*").order("performed_at",{ascending:false}),sb.from("stocks").select("*").order("name"),sb.from("diagnostics").select("*").order("created_at",{ascending:false}),sb.from("purchase_orders").select("*").order("created_at",{ascending:false}),sb.from("sales").select("*").order("sold_at",{ascending:false}),sb.from("journal_entries").select("*").order("created_at",{ascending:false}).limit(100)]);
  const failed=[p,a,s,i,int,st,d,po,sa,j].find(x=>x.error);if(failed?.error)setError(failed.error.message);else setData({companies,parcels:(p.data||[]) as Parcel[],animals:(a.data||[]) as Animal[],suppliers:(s.data||[]) as Supplier[],invoices:(i.data||[]) as Invoice[],interventions:(int.data||[]) as Intervention[],stocks:(st.data||[]) as Stock[],diagnostics:(d.data||[]) as Diagnostic[],purchases:(po.data||[]) as Purchase[],sales:(sa.data||[]) as Sale[],journal:(j.data||[]) as Journal[]});setLoading(false);
 },[cloud,session]);
 useEffect(()=>{load()},[load]);
 async function create(table:MutableTable,record:any){
  if(cloud){const {error}=await getSupabase().from(table).insert(record);if(error)throw error;await load();return}
  const key=table==="purchase_orders"?"purchases":table;const created={...record,id:crypto.randomUUID(),created_at:new Date().toISOString()};const entry:Journal={id:crypto.randomUUID(),company_id:record.company_id,event_type:`insert_${table}`,title:`Création ${table}`,details:{record_id:created.id},created_at:new Date().toISOString()};persist({...data,[key]:[created,...data[key as keyof Data] as any[]],journal:[entry,...data.journal]});
 }
 async function update(table:MutableTable,id:string,changes:any){
  if(cloud){const {error}=await getSupabase().from(table).update(changes).eq("id",id);if(error)throw error;await load();return}
  const key=table==="purchase_orders"?"purchases":table;const list=(data[key as keyof Data] as any[]).map(x=>x.id===id?{...x,...changes}:x);const entry:Journal={id:crypto.randomUUID(),company_id:changes.company_id,event_type:`update_${table}`,title:`Modification ${table}`,details:{record_id:id,changes},created_at:new Date().toISOString()};persist({...data,[key]:list,journal:[entry,...data.journal]});
 }
 async function remove(table:MutableTable,id:string){
  if(cloud){const {error}=await getSupabase().from(table).delete().eq("id",id);if(error)throw error;await load();return}
  const key=table==="purchase_orders"?"purchases":table;const old=(data[key as keyof Data] as any[]).find(x=>x.id===id);const entry:Journal={id:crypto.randomUUID(),company_id:old?.company_id,event_type:`delete_${table}`,title:`Suppression ${table}`,details:{record_id:id},created_at:new Date().toISOString()};persist({...data,[key]:(data[key as keyof Data] as any[]).filter(x=>x.id!==id),journal:[entry,...data.journal]});
 }
 return {data,loading,error,cloud,create,update,remove,reload:load};
}

function Dashboard({data,go}:{data:Data;go:(v:View)=>void}){
 const due=data.invoices.filter(i=>i.status==="pending");const hectares=data.parcels.reduce((s,p)=>s+Number(p.surface_ha),0);
 return <div className="view"><div className="welcome"><div><span>{new Date().toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).toUpperCase()}</span><h1>Centre de contrôle</h1><p>Données calculées depuis les enregistrements actifs.</p></div><div className="weather"><CloudSun/><b>12°C</b><small>Connexion météo à configurer</small></div></div><div className="metrics"><div className="metric"><CircleDollarSign/><div><span>Factures en attente</span><b>{money(due.reduce((s,x)=>s+Number(x.amount),0))}</b><small>{due.length} facture(s)</small></div></div><div className="metric"><Tractor/><div><span>Surface suivie</span><b>{hectares.toLocaleString("fr-FR")} ha</b><small>{data.parcels.length} parcelle(s)</small></div></div><div className="metric"><Beef/><div><span>Animaux présents</span><b>{data.animals.filter(a=>a.status==="Présent").length}</b><small>{data.animals.length} enregistré(s)</small></div></div><div className="metric"><ShoppingCart/><div><span>Fournisseurs actifs</span><b>{data.suppliers.filter(s=>s.status==="active").length}</b><small>{money(data.suppliers.reduce((s,x)=>s+Number(x.annual_volume||0),0))} / an</small></div></div></div><div className="dash-grid"><section className="card dashboard-list"><Title kicker="À TRAITER" title="Échéances fournisseurs" action={<button className="link" onClick={()=>go("invoices")}>Ouvrir les factures</button>}/>{due.length?due.slice(0,5).map(i=><div className="record-line" key={i.id}><FileText/><div><b>{i.supplier_name}</b><span>{i.invoice_number} · échéance {i.due_date||"non définie"}</span></div><strong>{money(i.amount)}</strong></div>):<div className="empty-small">Aucune facture en attente</div>}</section><section className="card dashboard-list"><Title kicker="JOURNAL" title="Activité récente" action={<button className="link" onClick={()=>go("journal")}>Voir tout</button>}/>{data.journal.slice(0,5).map(j=><div className="record-line" key={j.id}><Activity/><div><b>{j.title}</b><span>{new Date(j.created_at).toLocaleString("fr-FR")}</span></div></div>)}</section></div></div>
}

function CrudDialog({kind,open,onOpen,data,companyId,onCreate}:{kind:"parcel"|"animal"|"supplier"|"invoice";open:boolean;onOpen:(x:boolean)=>void;data:Data;companyId:string;onCreate:(table:any,record:any)=>Promise<void>}){
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);let table="";let record:any={company_id:companyId};
  if(kind==="parcel"){table="parcels";record={...record,name:f.get("name"),surface_ha:Number(f.get("surface")),culture:f.get("culture"),status:"Bon",cost_per_ha:Number(f.get("cost")||0)}}
  if(kind==="animal"){table="animals";record={...record,work_number:f.get("work"),national_number:f.get("national"),sex:f.get("sex"),breed:f.get("breed"),birth_date:f.get("birth")||null,mother_number:f.get("mother"),status:"Présent"}}
  if(kind==="supplier"){table="suppliers";record={...record,name:f.get("name"),category:f.get("category"),subcategory:f.get("subcategory"),email:f.get("email"),annual_volume:Number(f.get("volume")||0),status:"active"}}
  if(kind==="invoice"){table="invoices";record={...record,supplier_name:f.get("supplier"),invoice_number:f.get("number"),amount:Number(f.get("amount")),due_date:f.get("due")||null,status:"pending",duplicate:false}}
  try{await onCreate(table,record);toast.success("Enregistrement sauvegardé");onOpen(false)}catch(err:any){toast.error(err.message)}
 }
 const labels={parcel:"Nouvelle parcelle",animal:"Nouvel animal",supplier:"Nouveau fournisseur",invoice:"Nouvelle facture"};
 return <Dialog open={open} onOpenChange={onOpen}><DialogContent><DialogHeader><DialogTitle>{labels[kind]}</DialogTitle><DialogDescription>Les données seront enregistrées et ajoutées au Journal.</DialogDescription></DialogHeader><form onSubmit={submit} className="crud-form">
  <Field label="Entreprise"><select name="company" value={companyId} disabled>{data.companies.map(c=><option key={c.id}>{c.name}</option>)}</select></Field>
  {kind==="parcel"&&<><Field label="Nom"><input name="name" required/></Field><Field label="Surface ha"><input name="surface" type="number" step="0.01" required/></Field><Field label="Culture"><input name="culture" required/></Field><Field label="Coût par ha"><input name="cost" type="number" step="0.01"/></Field></>}
  {kind==="animal"&&<><Field label="Numéro travail"><input name="work" required/></Field><Field label="Numéro national"><input name="national"/></Field><Field label="Sexe"><select name="sex"><option>F</option><option>M</option></select></Field><Field label="Race"><input name="breed" defaultValue="Charolaise"/></Field><Field label="Naissance"><input name="birth" type="date"/></Field><Field label="Mère"><input name="mother"/></Field></>}
  {kind==="supplier"&&<><Field label="Nom"><input name="name" required/></Field><Field label="Catégorie"><input name="category" required/></Field><Field label="Sous-catégorie"><input name="subcategory"/></Field><Field label="E-mail"><input name="email" type="email"/></Field><Field label="Volume annuel €"><input name="volume" type="number"/></Field></>}
  {kind==="invoice"&&<><Field label="Fournisseur"><input name="supplier" required/></Field><Field label="Numéro"><input name="number" required/></Field><Field label="Montant €"><input name="amount" type="number" step="0.01" required/></Field><Field label="Échéance"><input name="due" type="date"/></Field></>}
  <button className="primary full" type="submit">Enregistrer</button></form></DialogContent></Dialog>
}

function Records({kind,data,companyId,create,update,remove}:{kind:"parcel"|"animal"|"supplier"|"invoice";data:Data;companyId:string;create:any;update:any;remove:any}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState("");const config={parcel:{title:"Parcelles & intrants",kicker:"GESTION CULTURES",table:"parcels",icon:Tractor},animal:{title:"Troupeau",kicker:"GESTION CHEPTEL",table:"animals",icon:Beef},supplier:{title:"Fournisseurs & achats",kicker:"RÉPERTOIRE FOURNISSEURS",table:"suppliers",icon:ShoppingCart},invoice:{title:"Mails & factures",kicker:"SUIVI ADMINISTRATIF",table:"invoices",icon:Inbox}}[kind];
 const rows=(data[config.table as keyof Data] as any[]).filter(x=>(companyId==="all"||x.company_id===companyId)&&JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));const activeCompany=companyId==="all"?data.companies[0]?.id:companyId;
 async function del(id:string){if(!confirm("Supprimer cet enregistrement ?"))return;try{await remove(config.table,id);toast.success("Enregistrement supprimé")}catch(e:any){toast.error(e.message)}}
 async function toggle(row:any){if(kind==="invoice")await update("invoices",row.id,{status:row.status==="paid"?"pending":"paid",company_id:row.company_id});else if(kind==="animal")await update("animals",row.id,{status:row.status==="Présent"?"Vendu":"Présent",company_id:row.company_id});else return;toast.success("Statut mis à jour")}
 return <div className="view"><Title kicker={`${config.kicker} · ${rows.length} ENREGISTREMENT(S)`} title={config.title} action={<button className="primary" onClick={()=>setOpen(true)} disabled={!activeCompany}><Plus/>Ajouter</button>}/><section className="card records-card"><div className="tools"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher…"/></label><Status>Données persistantes</Status></div><div className="record-table"><div className="record-row record-head"><span>Référence</span><span>Détails</span><span>Entreprise</span><span>Statut</span><span/></div>{rows.map(row=><div className="record-row" key={row.id}><span><b>{row.name||row.work_number||row.supplier_name}</b><small>{row.invoice_number||row.national_number||row.category||`${row.surface_ha} ha`}</small></span><span>{kind==="parcel"?`${row.culture} · ${money(row.cost_per_ha)}/ha`:kind==="animal"?`${row.sex||"-"} · ${row.breed||"-"}`:kind==="supplier"?money(row.annual_volume||0):`${money(row.amount)} · ${row.due_date||"sans échéance"}`}</span><span>{titleForCompany(data,row.company_id)}</span><button className="bare" onClick={()=>toggle(row)}><Status warn={row.status==="pending"||row.status==="À surveiller"}>{row.status}</Status></button><button className="delete" onClick={()=>del(row.id)} title="Supprimer"><Trash2/></button></div>)}</div>{!rows.length&&<div className="records-empty"><config.icon/><h3>Aucun enregistrement</h3><p>Ajoutez votre premier élément ou modifiez le filtre.</p></div>}</section><CrudDialog kind={kind} open={open} onOpen={setOpen} data={data} companyId={activeCompany} onCreate={create}/></div>
}

function activeId(data:Data,companyId:string){return companyId==="all"?data.companies[0]?.id:companyId}
function scoped<T extends {company_id:string}>(rows:T[],companyId:string){return rows.filter(x=>companyId==="all"||x.company_id===companyId)}

function ParcelsModule({data,companyId,create,update}:{data:Data;companyId:string;create:any;update:any}){
 const cid=activeId(data,companyId),parcels=scoped(data.parcels,companyId),interventions=scoped(data.interventions,companyId);const [open,setOpen]=useState(false);
 async function addIntervention(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),parcel=data.parcels.find(p=>p.id===f.get("parcel"));if(!cid||!parcel)return;const dose=Number(f.get("dose")||0),area=Number(f.get("area")||parcel.surface_ha),product=String(f.get("product")||"");try{await create("interventions",{company_id:cid,parcel_id:parcel.id,performed_at:f.get("date"),operation_type:f.get("type"),product,dose_kg_ha:dose,treated_area_ha:area,cost_per_ha:Number(f.get("cost")||0),weather:{source:"saisie",condition:f.get("weather")}});const stock=data.stocks.find(s=>s.company_id===cid&&s.name.toLowerCase().includes(product.toLowerCase()));if(stock&&dose>0)await update("stocks",stock.id,{quantity:Math.max(0,Number(stock.quantity)-dose*area),company_id:cid});toast.success("Intervention enregistrée et stock recalculé");setOpen(false)}catch(err:any){toast.error(err.message)}}
 return <div className="view"><Title kicker={`${parcels.length} PARCELLES · ${interventions.length} INTERVENTIONS`} title="Parcelles & intrants" action={<button className="primary" onClick={()=>setOpen(true)}><Plus/>Intervention</button>}/><div className="module-grid"><section className="card records-card"><h2>Parcelles suivies</h2>{parcels.map(p=><div className="module-row" key={p.id}><div><b>{p.name}</b><span>{p.culture} · {p.surface_ha} ha</span></div><Status warn={p.status!=="Bon"}>{p.status}</Status></div>)}</section><section className="card records-card"><h2>Dernières interventions</h2>{interventions.slice(0,8).map(i=><div className="module-row" key={i.id}><div><b>{i.operation_type} · {data.parcels.find(p=>p.id===i.parcel_id)?.name}</b><span>{i.product||"Sans produit"} · {i.treated_area_ha||0} ha · {i.performed_at}</span></div><strong>{money(Number(i.cost_per_ha||0)*Number(i.treated_area_ha||0))}</strong></div>)}{!interventions.length&&<p className="muted">Aucune intervention enregistrée.</p>}</section></div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Nouvelle intervention</DialogTitle><DialogDescription>La dose totale et le coût sont calculés avant validation.</DialogDescription></DialogHeader><form className="crud-form" onSubmit={addIntervention}><Field label="Parcelle"><select name="parcel" required>{parcels.map(p=><option value={p.id} key={p.id}>{p.name} · {p.surface_ha} ha</option>)}</select></Field><Field label="Date"><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></Field><Field label="Opération"><select name="type"><option>Fertilisation</option><option>Traitement</option><option>Semis</option><option>Récolte</option></select></Field><Field label="Produit"><input name="product" placeholder="Ammonitrate"/></Field><Field label="Dose kg/ha"><input name="dose" type="number" step="0.01"/></Field><Field label="Surface traitée ha"><input name="area" type="number" step="0.01"/></Field><Field label="Coût €/ha"><input name="cost" type="number" step="0.01"/></Field><Field label="Conditions"><select name="weather"><option>Sec</option><option>Humide</option><option>Vent faible</option></select></Field><button className="primary full">Valider l’intervention</button></form></DialogContent></Dialog></div>
}

function StockModule({data,companyId,create,update}:{data:Data;companyId:string;create:any;update:any}){const cid=activeId(data,companyId),rows=scoped(data.stocks,companyId);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await create("stocks",{company_id:cid,name:f.get("name"),category:f.get("category"),quantity:Number(f.get("quantity")),unit:f.get("unit"),minimum_quantity:Number(f.get("minimum")||0),unit_cost:Number(f.get("cost")||0)});(e.currentTarget as HTMLFormElement).reset();toast.success("Stock ajouté")}catch(err:any){toast.error(err.message)}}return <div className="view"><Title kicker="INVENTAIRE TEMPS RÉEL" title="Foin & stocks"/><div className="module-grid"><section className="card records-card"><h2>Niveaux de stock</h2>{rows.map(s=><div className="stock-line" key={s.id}><div><b>{s.name}</b><span>{s.category} · seuil {s.minimum_quantity} {s.unit}</span></div><strong className={Number(s.quantity)<=Number(s.minimum_quantity)?"danger":""}>{s.quantity} {s.unit}</strong><button className="secondary" onClick={()=>update("stocks",s.id,{quantity:Number(s.quantity)+1,company_id:s.company_id})}>+1</button><button className="secondary" onClick={()=>update("stocks",s.id,{quantity:Math.max(0,Number(s.quantity)-1),company_id:s.company_id})}>−1</button></div>)}</section><section className="card records-card"><h2>Ajouter un stock</h2><form className="crud-form" onSubmit={add}><Field label="Produit"><input name="name" required/></Field><Field label="Catégorie"><select name="category"><option>Fourrage</option><option>Engrais</option><option>Phytosanitaire</option><option>Carburant</option></select></Field><Field label="Quantité"><input name="quantity" type="number" step="0.01" required/></Field><Field label="Unité"><input name="unit" defaultValue="kg" required/></Field><Field label="Seuil d’alerte"><input name="minimum" type="number"/></Field><Field label="Coût unitaire"><input name="cost" type="number" step="0.01"/></Field><button className="primary full">Ajouter</button></form></section></div></div>}

function PassportModule({data,companyId,create}:{data:Data;companyId:string;create:any}){const cid=activeId(data,companyId),[photo,setPhoto]=useState<string>(),[scanned,setScanned]=useState(false);async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await create("animals",{company_id:cid,work_number:f.get("work"),national_number:f.get("national"),sex:f.get("sex"),breed:f.get("breed"),birth_date:f.get("birth")||null,mother_number:f.get("mother"),status:"Présent"});toast.success("Passeport validé et animal créé");setScanned(false);setPhoto(undefined)}catch(err:any){toast.error(err.message)}}function capture(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(file){setPhoto(URL.createObjectURL(file));setTimeout(()=>setScanned(true),600)}}return <div className="view"><Title kicker="PHOTO · OCR · VALIDATION HUMAINE" title="Scan passeport bovin"/><div className="scan-grid"><section className="card scanner"><div className={`scan-frame ${scanned?"done":""}`}>{photo?<img src={photo} alt="Passeport à analyser"/>:<><ScanLine/><p>Cadrez le passeport dans la zone</p></>}<i/></div><label className="capture"><Camera/>Prendre une photo<input type="file" accept="image/*" capture="environment" onChange={capture}/></label></section><section className="card extracted"><h2>Données reconnues</h2><div className="human"><ScanLine/><div><b>Validation obligatoire</b><span>Le moteur OCR est simulé en V1 : vérifiez chaque champ.</span></div></div>{scanned?<form className="crud-form" onSubmit={save}><Field label="N° travail"><input name="work" defaultValue={`AP-${Date.now().toString().slice(-4)}`} required/></Field><Field label="N° national"><input name="national" defaultValue="FR 18 "/></Field><Field label="Sexe"><select name="sex"><option>F</option><option>M</option></select></Field><Field label="Race"><input name="breed" defaultValue="Charolaise"/></Field><Field label="Naissance"><input name="birth" type="date"/></Field><Field label="N° mère"><input name="mother"/></Field><button className="primary full"><Check/>Valider et créer</button></form>:<div className="empty"><ScanLine/><p>Ajoutez une photo pour démarrer l’extraction.</p></div>}</section></div></div>}

function DiagnosisModule({data,companyId,create}:{data:Data;companyId:string;create:any}){const cid=activeId(data,companyId),parcels=scoped(data.parcels,companyId),[ready,setReady]=useState(false),[preview,setPreview]=useState<string>();function inspect(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(f){setPreview(URL.createObjectURL(f));setTimeout(()=>setReady(true),700)}}async function validate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await create("diagnostics",{company_id:cid,parcel_id:f.get("parcel")||null,disease:f.get("disease"),confidence:87,recommendation:f.get("recommendation"),status:"validated"});toast.success("Diagnostic validé et historisé");setReady(false);setPreview(undefined)}catch(err:any){toast.error(err.message)}}return <div className="view"><Title kicker="AIDE À LA DÉCISION · VALIDATION HUMAINE" title="Diagnostic blé"/><div className="diag-grid"><section className="card crop"><div>{preview?<img src={preview} alt="Culture analysée"/>:<Wheat/>}<i/></div><label className="capture"><Upload/>Photographier la culture<input type="file" accept="image/*" capture="environment" onChange={inspect}/></label></section><section className="card diagnosis"><h2>Analyse visuelle</h2>{ready?<><Status>Confiance 87 %</Status><div className="disease"><label><b>Rouille brune probable</b><span>87 %</span></label><progress value="87" max="100"/></div><p>Présence de pustules orange dispersées sur le limbe. Confirmez avant toute intervention.</p></>:<p className="muted">Prenez une photo nette des feuilles atteintes.</p>}</section><section className="card recommendation"><Sprout/><span>RECOMMANDATION</span><h2>Décision agronomique</h2>{ready&&<form className="crud-form" onSubmit={validate}><Field label="Parcelle"><select name="parcel">{parcels.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><Field label="Diagnostic"><input name="disease" defaultValue="Rouille brune probable"/></Field><Field label="Recommandation"><textarea name="recommendation" defaultValue="Surveiller l’évolution à 48 h et consulter le technicien avant traitement."/></Field><button className="primary full">Valider le diagnostic</button></form>}</section></div></div>}

function PurchaseModule({data,companyId,create,update}:{data:Data;companyId:string;create:any;update:any}){const cid=activeId(data,companyId),orders=scoped(data.purchases,companyId),suppliers=scoped(data.suppliers,companyId);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await create("purchase_orders",{company_id:cid,supplier_id:f.get("supplier")||null,need_text:f.get("need"),quantity:f.get("quantity"),estimated_amount:Number(f.get("amount")||0),status:"draft"});(e.currentTarget as HTMLFormElement).reset();toast.success("Demande d’achat créée")}catch(err:any){toast.error(err.message)}}return <div className="view"><Title kicker="FOURNISSEURS · COMMANDES · VALIDATION" title="Fournisseurs & achats"/><div className="module-grid"><section className="card records-card"><h2>Nouvelle demande</h2><form className="crud-form" onSubmit={add}><Field label="Besoin"><input name="need" placeholder="Foin, carburant, semences…" required/></Field><Field label="Fournisseur"><select name="supplier"><option value="">À consulter</option>{suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></Field><Field label="Quantité"><input name="quantity" placeholder="20 tonnes"/></Field><Field label="Budget estimé"><input name="amount" type="number" step="0.01"/></Field><button className="primary full">Créer le brouillon</button></form></section><section className="card records-card"><h2>Commandes</h2>{orders.map(o=><div className="module-row" key={o.id}><div><b>{o.need_text}</b><span>{o.quantity||"Quantité à préciser"} · {money(Number(o.estimated_amount||0))}</span></div><button className={o.status==="validated"?"secondary":"primary"} disabled={o.status==="validated"} onClick={()=>update("purchase_orders",o.id,{status:"validated",company_id:o.company_id})}>{o.status==="validated"?"Validée":"Valider"}</button></div>)}{!orders.length&&<p className="muted">Aucune commande pour le moment.</p>}</section></div><section className="card records-card supplier-strip"><h2>Répertoire</h2>{suppliers.map(s=><div className="module-row" key={s.id}><div><b>{s.name}</b><span>{s.category} · {s.email||"sans e-mail"}</span></div><strong>{money(s.annual_volume||0)}/an</strong></div>)}</section></div>}

function FinanceModule({data,companyId,create}:{data:Data;companyId:string;create:any}){const cid=activeId(data,companyId),invoices=scoped(data.invoices,companyId),sales=scoped(data.sales,companyId),expenses=invoices.reduce((n,x)=>n+Number(x.amount),0),income=sales.reduce((n,x)=>n+Number(x.amount),0);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await create("sales",{company_id:cid,label:f.get("label"),amount:Number(f.get("amount")),sold_at:f.get("date"),category:f.get("category")});(e.currentTarget as HTMLFormElement).reset();toast.success("Recette enregistrée")}catch(err:any){toast.error(err.message)}}return <div className="view"><Title kicker="TRÉSORERIE CONSOLIDÉE" title="Finances"/><div className="simple-grid"><section className="card stat"><TrendingUp/><span>Recettes</span><b>{money(income)}</b></section><section className="card stat"><CircleDollarSign/><span>Dépenses</span><b>{money(expenses)}</b></section><section className="card stat"><Gauge/><span>Solde</span><b className={income-expenses<0?"danger":""}>{money(income-expenses)}</b></section><section className="card stat"><FileText/><span>Impayés</span><b>{money(invoices.filter(i=>i.status==="pending").reduce((n,x)=>n+Number(x.amount),0))}</b></section></div><div className="module-grid"><section className="card chart"><h2>Répartition</h2><div className="finance-bars"><div style={{height:`${Math.max(10,income/Math.max(income,expenses,1)*100)}%`}}><span>Recettes</span></div><div className="expense" style={{height:`${Math.max(10,expenses/Math.max(income,expenses,1)*100)}%`}}><span>Dépenses</span></div></div></section><section className="card records-card"><h2>Ajouter une recette</h2><form className="crud-form" onSubmit={add}><Field label="Libellé"><input name="label" required/></Field><Field label="Montant"><input name="amount" type="number" step="0.01" required/></Field><Field label="Date"><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></Field><Field label="Catégorie"><select name="category"><option>Cultures</option><option>Élevage</option><option>Subvention</option><option>Autre</option></select></Field><button className="primary full">Enregistrer</button></form></section></div></div>}

function CamerasModule(){const [alert,setAlert]=useState(false);return <div className="view"><Title kicker="SURVEILLANCE · MODE DÉMONSTRATION" title="Caméras DMSS" action={<Status warn>Connecteur à renseigner</Status>}/><div className="cam-grid">{["Stabulation nord","Aire de vêlage","Hangar matériel","Cour principale"].map((name,i)=><section className="card cam" key={name}><div className="cam-view"><Video/><span>FLUX {i+1} · APERÇU SIMULÉ</span>{alert&&i===1&&<b className="camera-alert">Mouvement détecté</b>}</div><footer><div><b>{name}</b><span>{alert&&i===1?"Alerte active":"En ligne · simulation"}</span></div><button onClick={()=>{setAlert(!alert);toast.success(alert?"Alerte acquittée":"Alerte de test créée")}}><Bell/></button></footer></section>)}</div></div>}

function PacModule({data,companyId}:{data:Data;companyId:string}){const parcels=scoped(data.parcels,companyId);function exportPac(){const csv=["Parcelle;Culture;Surface_ha",...parcels.map(p=>`${p.name};${p.culture};${p.surface_ha}`)].join("\n");download(csv,"export-pac.csv","text/csv")}return <div className="view"><Title kicker="REGISTRE PARCELLAIRE · PRÉPARATION PAC" title="PAC & Géoportail" action={<button className="primary" onClick={exportPac}><Download/>Exporter</button>}/><div className="module-grid"><section className="card pac-map"><Map/><div>{parcels.map((p,i)=><i key={p.id} style={{left:`${12+(i*23)%70}%`,top:`${15+(i*29)%60}%`,background:data.companies.find(c=>c.id===p.company_id)?.color}} title={p.name}>{i+1}</i>)}</div><small>Fond cartographique schématique — connecteur Géoportail à configurer</small></section><section className="card records-card"><h2>Déclaration préparatoire</h2>{parcels.map((p,i)=><div className="module-row" key={p.id}><div><b>{i+1}. {p.name}</b><span>{p.culture}</span></div><strong>{p.surface_ha} ha</strong></div>)}<p className="muted">Surface totale : {parcels.reduce((n,p)=>n+Number(p.surface_ha),0).toLocaleString("fr-FR")} ha</p></section></div></div>}

const marketRows=[['Blé tendre','228 €/t','+1,8 %'],['Colza','487 €/t','−0,6 %'],['Orge','201 €/t','+0,4 %'],['Bovin U','5,84 €/kg','+1,1 %']];
function ExternalModule({kind}:{kind:"markets"|"weather"}){return <div className="view"><Title kicker="DONNÉES INDICATIVES · MODE DÉMONSTRATION" title={kind==="markets"?"Cotations agricoles":"Météo exploitation"} action={<Status warn>API à connecter</Status>}/>{kind==="markets"?<section className="card records-card">{marketRows.map(r=><div className="module-row" key={r[0]}><div><b>{r[0]}</b><span>Cotation différée de démonstration</span></div><strong>{r[1]} · {r[2]}</strong></div>)}</section>:<div className="weather-days">{[["Aujourd’hui",CloudSun,"16°","Vent 12 km/h"],["Demain",CloudRain,"12°","Pluie 4 mm"],["Dimanche",CloudSun,"18°","Fenêtre de traitement"],["Lundi",CloudSun,"19°","Vent 8 km/h"]].map(([d,I,t,x]:any)=><section className="card" key={d}><I/><b>{d}</b><strong>{t}</strong><span>{x}</span></section>)}</div>}</div>}

function download(content:string,name:string,type:string){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}

function JournalView({data,companyId}:{data:Data;companyId:string}){const rows=data.journal.filter(j=>companyId==="all"||j.company_id===companyId);function exportCsv(){download(["Date;Entreprise;Événement;Titre",...rows.map(j=>`${j.created_at};${j.company_id?titleForCompany(data,j.company_id):"Système"};${j.event_type};${j.title}`)].join("\n"),"journal-agripilot.csv","text/csv")}return <div className="view"><Title kicker="AUDIT DES MODIFICATIONS" title="Journal & traçabilité" action={<button className="primary" onClick={exportCsv}><Download/>Exporter CSV</button>}/><section className="card journal">{rows.map(j=><div key={j.id}><i><Activity/></i><main><time>{new Date(j.created_at).toLocaleString("fr-FR")}</time><h3>{j.title}</h3><p>{j.event_type}</p><span>{j.company_id?titleForCompany(data,j.company_id):"Système"}</span><span>Identifiant {String(j.details?.record_id||j.id).slice(0,8)}</span></main></div>)}</section></div>}

function VoiceAssistant({open,onOpen,data,companyId,create}:{open:boolean;onOpen:(x:boolean)=>void;data:Data;companyId:string;create:any}){const [text,setText]=useState(""),[listening,setListening]=useState(false),cid=activeId(data,companyId);function listen(){const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech){toast.error("La reconnaissance vocale n’est pas disponible dans ce navigateur");return}const r=new Speech();r.lang="fr-FR";r.interimResults=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onresult=(e:any)=>setText(e.results[0][0].transcript);r.start()}async function confirm(){const lower=text.toLowerCase();try{if(lower.includes("naissance")||lower.includes("veau")){await create("animals",{company_id:cid,work_number:`VOC-${Date.now().toString().slice(-4)}`,sex:lower.includes("mâle")?"M":"F",breed:"Charolaise",birth_date:new Date().toISOString().slice(0,10),status:"Présent"})}else if(lower.includes("achat")||lower.includes("commande")){await create("purchase_orders",{company_id:cid,need_text:text,quantity:"À préciser",estimated_amount:0,status:"draft"})}else{const parcel=data.parcels.find(p=>lower.includes(p.name.toLowerCase()))||data.parcels.find(p=>p.company_id===cid);if(!parcel)throw new Error("Aucune parcelle disponible");await create("interventions",{company_id:cid,parcel_id:parcel.id,performed_at:new Date().toISOString().slice(0,10),operation_type:lower.includes("sem")?"Semis":lower.includes("trait")?"Traitement":"Intervention vocale",product:"",dose_kg_ha:0,treated_area_ha:parcel.surface_ha,cost_per_ha:0,weather:{source:"commande vocale"}})}toast.success("Commande validée et enregistrée");onOpen(false);setText("")}catch(err:any){toast.error(err.message)}}return <Dialog open={open} onOpenChange={onOpen}><DialogContent className="voice-dialog"><DialogHeader><DialogTitle>Assistant vocal AgriPilot</DialogTitle><DialogDescription>Dictez une naissance, une intervention ou un besoin d’achat. Vous validez toujours avant l’enregistrement.</DialogDescription></DialogHeader><button className={`voice-orb ${listening?"on":""}`} onClick={listen}><Mic/></button><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Ex. J’ai traité Les Bordos aujourd’hui…"/><div className="samples"><button onClick={()=>setText("Naissance d’un veau femelle aujourd’hui")}>Naissance d’un veau</button><button onClick={()=>setText("Traitement de la parcelle Les Bordos aujourd’hui")}>Intervention parcelle</button><button onClick={()=>setText("Commande de 20 tonnes de foin")}>Besoin d’achat</button></div><button className="primary full" disabled={!text.trim()} onClick={confirm}><Check/>Vérifier et enregistrer</button></DialogContent></Dialog>}

export default function Page(){
 const cloud=isSupabaseConfigured(),[session,setSession]=useState<Session|null>(null),[authReady,setAuthReady]=useState(!cloud),[view,setView]=useState<View>("dashboard"),[company,setCompany]=useState("all"),[menu,setMenu]=useState(false),[terrain,setTerrain]=useState(false),[voice,setVoice]=useState(false);const crm=useCrmData(session);
 useEffect(()=>{if(!cloud)return;const sb=getSupabase();sb.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true)});const {data}=sb.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[cloud]);
 useEffect(()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>undefined)},[]);
 async function logout(){if(cloud)await getSupabase().auth.signOut();setSession(null)}
 if(!authReady)return <main className="loading-page">Chargement sécurisé…</main>;if(cloud&&!session)return <Auth onSession={setSession}/>;
 const currentCompany=company==="all"?null:company;let content:React.ReactNode;
 if(view==="dashboard")content=<Dashboard data={crm.data} go={setView}/>;else if(view==="parcels")content=<ParcelsModule companyId={company} {...crm}/>;else if(view==="animals")content=<Records kind="animal" companyId={company} {...crm}/>;else if(view==="passport")content=<PassportModule companyId={company} {...crm}/>;else if(view==="diagnosis")content=<DiagnosisModule companyId={company} {...crm}/>;else if(view==="stocks")content=<StockModule companyId={company} {...crm}/>;else if(view==="cameras")content=<CamerasModule/>;else if(view==="pac")content=<PacModule data={crm.data} companyId={company}/>;else if(view==="suppliers")content=<PurchaseModule companyId={company} {...crm}/>;else if(view==="invoices")content=<Records kind="invoice" companyId={company} {...crm}/>;else if(view==="finance")content=<FinanceModule companyId={company} {...crm}/>;else if(view==="markets"||view==="weather")content=<ExternalModule kind={view}/>;else content=<JournalView data={crm.data} companyId={company}/>;
 return <div className={terrain?"app terrain":"app"}><aside className={menu?"sidebar open":"sidebar"}><div className="brand"><i><Leaf/></i><div><b>AgriPilot</b><span>OS Agricole</span></div><button onClick={()=>setMenu(false)}><X/></button></div><button className="company" onClick={()=>{const opts=["all",...crm.data.companies.map(c=>c.id)];setCompany(opts[(opts.indexOf(company)+1)%opts.length])}}><i>{currentCompany?titleForCompany(crm.data,currentCompany)[0]:"G"}</i><div><span>Vue active</span><b>{currentCompany?titleForCompany(crm.data,currentCompany):"Toutes les entreprises"}</b></div><ChevronDown/></button><nav>{nav.map(([id,label,I])=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id as View);setMenu(false)}}><I/><span>{label}</span>{id==="invoices"&&crm.data.invoices.filter(i=>i.status==="pending").length>0&&<b>{crm.data.invoices.filter(i=>i.status==="pending").length}</b>}</button>)}</nav><footer><button><Settings/>Réglages</button>{cloud&&<button onClick={logout}><LogOut/>Déconnexion</button>}<div><i>{session?.user.email?.[0]?.toUpperCase()||"AC"}</i><span><b>{session?.user.email||"Mode démonstration"}</b><small>{cloud?"Compte Supabase":"Stockage local temporaire"}</small></span></div></footer></aside><main className="content"><header><button className="menu" onClick={()=>setMenu(true)}><Menu/></button><b>{nav.find(x=>x[0]===view)?.[1]}</b><div>{!cloud&&<span className="demo-badge">MODE LOCAL · CONNECTER SUPABASE</span>}<button className="mode" onClick={()=>setTerrain(!terrain)}><Tractor/>{terrain?"Mode cockpit":"Mode terrain"}</button><button><Bell/></button></div></header>{crm.error&&<div className="error-banner">Erreur Supabase : {crm.error}</div>}{crm.loading?<main className="loading-page">Chargement des données…</main>:content}</main><button className="voice-fab" onClick={()=>setVoice(true)}><Mic/><span>Assistant</span></button>{terrain&&<div className="bottom"><button onClick={()=>setView("dashboard")}><Gauge/>Accueil</button><button onClick={()=>setView("parcels")}><Tractor/>Parcelle</button><button className="mic" onClick={()=>setVoice(true)}><Mic/></button><button onClick={()=>setView("animals")}><Beef/>Troupeau</button><button onClick={()=>setView("journal")}><ClipboardCheck/>Journal</button></div>}<VoiceAssistant open={voice} onOpen={setVoice} data={crm.data} companyId={company} create={crm.create}/><Toaster position="top-right" richColors/></div>
}
